
/*
                "T: froggy_doesnt_like",
                "T: pattete_error_invalid_hex |||[]|||",
                "T: could_not_create_palette",
                "T: invalid_format_object_inter_rule_delimiter",
                "T: error_data_unavailable",
                "T: provide_palette_name",
                "T: available_color_palettes",
                "T: color_palette_does_not_exist",
                "T: state_cleared",
                "T: provide_file_name",
                "T: file_does_not_exist",
                "T: no_permission_to_delete_file",
                "T: cannot_delete_file",
                "T: provide_time_format",
                "T: arg_too_long",
                "T: directory_does_not_exist",
                "T: file_already_exists",
                "T: file_created",
                "T: hello_froggy",
                "T: basic_commands_0",
                "T: basic_commands_1",
                "T: basic_commands_2",
                "T: basic_commands_3",
                "T: basic_commands_4",
                "T: basic_commands_5",
                "T: basic_commands_6",
                "T: basic_commands_7",
                "T: basic_commands_8",
                "T: basic_commands_9",
                "T: basic_commands_10",
                "T: basic_commands_11",
                "T: basic_commands_12",
                "T: basic_commands_13",
                "T: basic_commands_14",
                "T: basic_commands_15",
                "T: basic_commands_16",
                "T: basic_commands_17",
                "T: basic_commands_18",
                "T: basic_commands_19",
                "T: basic_commands_20",
                "T: provide_directory_name",
                "T: directory_does_not_exist",
                "T: directory_empty",
                "T: no_state_found",
                "T: state_loaded",
                "T: provide_macro_name",
                "T: available_macros",
                "T: no_macros_found",
                "T: macro_does_not_exist",
                "T: missing_file_args",
                "T: no_permission_to_edit_file",
                "T: lilypad_save_exit",
                "T: provide_valid_property_type",
                "T: available_properties",
                "T: provide_valid_value_0_1",
                "T: properties_updated",
                "T: documentation_opened",
                "T: provide_text_to_display",
                "T: state_saved",
                "T: cannot_create_directories",
                "T: directory_already_exists",
                "T: directory_created",
                "T: no_permission_to_read_file",
                "T: provide_valid_program",
                "T: available_programs",
                "T: lilypad_exit",
                "T: no_permission_to_run_program",
                "T: provide_path",
                "T: nmt_greeting_1",
                "T: nmt_greeting_2 |||[]|||",
                "T: bullfrog_commands_0",
                "T: bullfrog_commands_1",
                "T: bullfrog_commands_2",
                "T: bullfrog_commands_3",
                "T: bullfrog_commands_4",
                "T: bullfrog_commands_5",
                "T: bullfrog_commands_6",
                "T: bullfrog_commands_7",
                "T: bullfrog_commands_8",
                "T: bullfrog_commands_9",
                "T: bullfrog_commands_10",
                "T: bullfrog_commands_11",
                "T: bullfrog_commands_12",
                "T: invalid_args_provide_1_0",
                "T: spinner_does_not_exist",
                "T: available_spinners",
                "T: no_urgent_state_found",
                "T: doesnt_know |||[]|||",
                "T: saving_file",
                "T: saving_done",
                "T: date_short_sunday",
                "T: date_short_monday",
                "T: date_short_tuesday",
                "T: date_short_wednesday",
                "T: date_short_thursday",
                "T: date_short_friday",
                "T: date_short_saturday",
                "T: date_long_sunday",
                "T: date_long_monday",
                "T: date_long_tuesday",
                "T: date_long_wednesday",
                "T: date_long_thursday",
                "T: date_long_friday",
                "T: date_long_saturday",
                "T: date_short_january",
                "T: date_short_february",
                "T: date_short_march",
                "T: date_short_april",
                "T: date_short_may",
                "T: date_short_june",
                "T: date_short_july",
                "T: date_short_august",
                "T: date_short_september",
                "T: date_short_october",
                "T: date_short_november",
                "T: date_short_december",

*/
const ENGLISH_LOCAL = [
    "Froggy doesn't like that. >:(",
    `PaletteError: |||[]||| is an invalid hex color.`,
    "Could not create palette.",
    "Invalid FormatObject (INTER-RULE DELIMITER) syntax.",
    "Error Data UNAVAILABLE",
    "Please provide a color palette name.",
    `* Available color palettes *`,
    `"Color palette does not exist."`,
    `State cleared.`,
    "Please provide a file name.",
    "File does not exist.",
    "You do not have permission to delete this file.",
    "You cannot delete this file.",
    "Please provide a time format.",
    "The argument is too long.",
    "Directory does not exist.",
    "File already exists.",
    "File created.",
    "Hello, I'm Froggy! ^v^",
    "* A few basic froggyOS commands *",
    "changepalette [palette]. . . . Changes the color palette.",
    "clear. . . . . . . . . . . . . Clears the terminal output.",
    "clearstate . . . . . . . . . . Clears froggyOS state.",
    "croak [file] . . . . . . . . . Deletes the file.",
    "ribbit [text]. . . . . . . . . Displays the text.",
    "formattime [format]. . . . . . Changes the time format.",
    "hatch [file] . . . . . . . . . Creates a file.",
    "hello. . . . . . . . . . . . . Displays a greeting message.",
    "help . . . . . . . . . . . . . Displays this message.",
    "hop [directory]. . . . . . . . Moves to a directory.",
    "list . . . . . . . . . . . . . Lists files and subdirectories in the current                                directory.",
    "listdrives . . . . . . . . . . Lists all drives.",
    "loadstate. . . . . . . . . . . Load froggyOS state.",
    "meta [file]. . . . . . . . . . Edits a file.",
    "metaprop [file] [perm] [0/1] . Edits a file's properties.",
    "opendocumentation. . . . . . . Opens the froggyOS documentation.",
    "savestate. . . . . . . . . . . Save froggyOS state.",
    "spawn [directory]. . . . . . . Creates a directory.",
    "spy [file] . . . . . . . . . . Reads the file.",
    "swimto [program] . . . . . . . Start a program.",
    "Please provide a directory name.",
    "Directory does not exist.",
    "This directory is empty.",
    "No state found.",
    "State loaded.",
    "Please provide a macro name.",
    `* Available macros *`,
    "No macros found.",
    "Macro does not exist.",
    `Missing file argument(s).`,
    "You do not have permission to edit this file.",
    "* press ESC to save and exit lilypad *",
    "Please provide a valid property type.",
    "* Available properties *",
    "Please provide a valid value. 0 or 1.",
    "properties updated.",
    "Documentation opened in a new window.",
    "Please provide text to display.",
    "State saved. May need to loadstate for some changes to take effect.",
    "You cannot create directories in this directory.",
    "Directory already exists.",
    "Directory created.",
    "You do not have permission to read this file.",
    "Please provide a valid program.",
    "* Available programs *",
    "* press ESC to exit lilypad *",
    "You do not have permission to run this program.",
    "Please provide a path.",
    "Type ‘help’ to receive support with commands, and possibly navigation.",
    `* Welcome to froggyOS, version |||[]||| *`,
    "* A few bullfrog commands *",
    "[[BULLFROG]]changepath [path] - Changes the path of the terminal",
    "[[BULLFROG]]greeting - Displays the greeting message",
    "[[BULLFROG]]help - Displays this message",
    "[[BULLFROG]]setstatbar [text] - Changes the text in the status bar",
    "[[BULLFROG]]statbarlock [0/1] - Locks the status bar from updating",
    "[[BULLFROG]]showspinner [0/1] - Toggles the loading spinner",
    "[[BULLFROG]]debugmode [0/1] - Toggles debug mode",
    "[[BULLFROG]]setspinner [spinner] - Changes the loading spinner",
    "[[BULLFROG]]urgentsavestate - saves state for reloading",
    "[[BULLFROG]]urgentloadstate - loads state for reloading",
    "[[BULLFROG]]urgentclearstate - clears reload state",
    "[[BULLFROG]]autoloadstate - loads state",
    "Invalid argument. Please provide '1' or '0'.",
    "Spinner does not exist.",
    "* Available spinners *",
    "No urgent state found.",
    `Froggy doesn't know "|||[]|||", sorry.`,
    "Saving file...",
    "Done! ^v^",
    "Date_Sun",
    "Date_Mon",
    "Date_Tue",
    "Date_Wed",
    "Date_Thu",
    "Date_Fri",
    "Date_Sat",
    "Date_Sunday",
    "Date_Monday",
    "Date_Tuesday",
    "Date_Wednesday",
    "Date_Thursday",
    "Date_Friday",
    "Date_Saturday",
    "Date_Jan",
    "Date_Feb",
    "Date_Mar",
    "Date_Apr",
    "Date_May",
    "Date_Jun",
    "Date_Jul",
    "Date_Aug",
    "Date_Sep",
    "Date_Oct",
    "Date_Nov",
    "Date_Dec",
    "Date_January",
    "Date_February",
    "Date_March",
    "Date_April",
    "Date_May",
    "Date_June",
    "Date_July",
    "Date_August",
    "Date_September",
    "Date_October",
    "Date_November",
    "Date_December",
]

const config = {
    // settings as files
    debugMode: null,
    version: null,
    colorPalette: null,
    showSpinner: null,
    currentSpinner: null,
    timeFormat: null,
    updateStatBar: null,
    allowedProgramDirectories: null,
    dissallowSubdirectoriesIn: null,
    language: null,

    // immutable settings
    currentPath: 'C:/Home',
    commandHistory: [],
    commandHistoryIndex: -1,
    spinnerIndex: 0,
    currentProgram: "cli",
    savingFile: false,
    programList: ["cli", "lilypad"],
    programSession: 0,
    errorText: "<span class='error'><span class='error-text'>!!ERROR!!</span> -</span>",

    // filesystem
    fileSystem: {
        "Lang:": [
            { name: "BRAIN_BASE", properties: {read: true, write: false, hidden: true}, data: JSON.parse(JSON.stringify(ENGLISH_LOCAL)) },
            { name: "eng", properties: {read: true, write: true, hidden: false}, data: JSON.parse(JSON.stringify(ENGLISH_LOCAL)) },
            { name: "nmt", properties: {read: true, write: true, hidden: false}, data: [
                "T: froggy_doesnt_like",
                "T: pattete_error_invalid_hex |||[]|||",
                "T: could_not_create_palette",
                "T: invalid_format_object_inter_rule_delimiter",
                "T: error_data_unavailable",
                "T: provide_palette_name",
                "T: available_color_palettes",
                "T: color_palette_does_not_exist",
                "T: state_cleared",
                "T: provide_file_name",
                "T: file_does_not_exist",
                "T: no_permission_to_delete_file",
                "T: cannot_delete_file",
                "T: provide_time_format",
                "T: arg_too_long",
                "T: directory_does_not_exist",
                "T: file_already_exists",
                "T: file_created",
                "T: hello_froggy",
                "T: basic_commands_0",
                "T: basic_commands_1",
                "T: basic_commands_2",
                "T: basic_commands_3",
                "T: basic_commands_4",
                "T: basic_commands_5",
                "T: basic_commands_6",
                "T: basic_commands_7",
                "T: basic_commands_8",
                "T: basic_commands_9",
                "T: basic_commands_10",
                "T: basic_commands_11",
                "T: basic_commands_12",
                "T: basic_commands_13",
                "T: basic_commands_14",
                "T: basic_commands_15",
                "T: basic_commands_16",
                "T: basic_commands_17",
                "T: basic_commands_18",
                "T: basic_commands_19",
                "T: basic_commands_20",
                "T: provide_directory_name",
                "T: directory_does_not_exist",
                "T: directory_empty",
                "T: no_state_found",
                "T: state_loaded",
                "T: provide_macro_name",
                "T: available_macros",
                "T: no_macros_found",
                "T: macro_does_not_exist",
                "T: missing_file_args",
                "T: no_permission_to_edit_file",
                "T: lilypad_save_exit",
                "T: provide_valid_property_type",
                "T: available_properties",
                "T: provide_valid_value_0_1",
                "T: properties_updated",
                "T: documentation_opened",
                "T: provide_text_to_display",
                "T: state_saved",
                "T: cannot_create_directories",
                "T: directory_already_exists",
                "T: directory_created",
                "T: no_permission_to_read_file",
                "T: provide_valid_program",
                "T: available_programs",
                "T: lilypad_exit",
                "T: no_permission_to_run_program",
                "T: provide_path",
                "T: nmt_greeting_1",
                "T: nmt_greeting_2 |||[]|||",
                "T: bullfrog_commands_0",
                "T: bullfrog_commands_1",
                "T: bullfrog_commands_2",
                "T: bullfrog_commands_3",
                "T: bullfrog_commands_4",
                "T: bullfrog_commands_5",
                "T: bullfrog_commands_6",
                "T: bullfrog_commands_7",
                "T: bullfrog_commands_8",
                "T: bullfrog_commands_9",
                "T: bullfrog_commands_10",
                "T: bullfrog_commands_11",
                "T: bullfrog_commands_12",
                "T: invalid_args_provide_1_0",
                "T: spinner_does_not_exist",
                "T: available_spinners",
                "T: no_urgent_state_found",
                "T: doesnt_know |||[]|||",
                "T: saving_file",
                "T: saving_done",
                "T: date_short_sunday",
                "T: date_short_monday",
                "T: date_short_tuesday",
                "T: date_short_wednesday",
                "T: date_short_thursday",
                "T: date_short_friday",
                "T: date_short_saturday",
                "T: date_long_sunday",
                "T: date_long_monday",
                "T: date_long_tuesday",
                "T: date_long_wednesday",
                "T: date_long_thursday",
                "T: date_long_friday",
                "T: date_long_saturday",
                "T: date_short_january",
                "T: date_short_february",
                "T: date_short_march",
                "T: date_short_april",
                "T: date_short_may",
                "T: date_short_june",
                "T: date_short_july",
                "T: date_short_august",
                "T: date_short_september",
                "T: date_short_october",
                "T: date_short_november",
                "T: date_short_december",
            ] },
        ],
        "Settings:": [
            { name: "language", properties: {read: true, write: true, hidden: false}, data: ["eng"] },
            { name: "debugMode", properties: {read: true, write: true, hidden: false}, data: ["false"] },
            { name: "colorPalette", properties: {read: true, write: true, hidden: false}, data: ["standard"] },
            { name: "version", properties: {read: true, write: true, hidden: false}, data: ["1.9"] },
            { name: "showSpinner", properties: {read: true, write: true, hidden: false}, data: ["false"] },
            { name: "currentSpinner", properties: {read: true, write: true, hidden: false}, data: ["default"] },
            { name: "timeFormat", properties: {read: true, write: true, hidden: false}, data: ["w. y/mn/d h:m:s"] },
            { name: "updateStatBar", properties: {read: true, write: true, hidden: false}, data: ["true"] },
            { name: "allowedProgramDirectories", properties: {read: true, write: false, hidden: false}, data: ["D:/Programs"] },
            { name: "dissallowSubdirectoriesIn", properties: {read: true, write: false, hidden: false}, data: ["D:/Programs", "D:/Macros", "D:/Program-Data", "D:/Palettes", "D:/Spinners"] },
        ],
        "C:": [],   
        "C:/Home": [
            { name: "welcome!", properties: {read: true, write: true, hidden: false}, data: ['Hello!', "Welcome to FroggyOS.", "Type 'help' for a list of commands.", "Have fun! ^v^"] },
        ],
        "C:/Docs": [],
        "D:": [], 
        "D:/Programs": [
            { name: "cli", properties: {read: false, write: false, hidden: true}, data: ["str cli = 'this program is hardcoded into froggyOS'", "endprog"] },
            { name: "lilypad", properties: {read: false, write: false, hidden: true}, data: ["str lilypad = 'this program is hardcoded into froggyOS'", "endprog"] },
            { name: "test", properties: {read: true, write: true, hidden: false}, data: [
                "out 'before loop'",
                "int i = 0",
                "loop { v:i < 1000 }",
                "out v:i",
                "set i = v:i + 1",
                "wait 0",
                "endloop",
                "out 'after loop'",
                "endprog",
            ] },
            { name: "help", properties: {read: true, write: false, hidden: false}, data: [
                "str category = ''",
                "out 'Choose a category: '",
                "prompt 0 category OS File Directory Other",
                "if {v:category == 'OS'}",
                "out 'clearstate. . . .clears froggyOS state'",
                "out 'loadstate . . . .loads froggyOS state'",
                "out 'savestate . . . .saves froggyOS state'",
                "out 'swimto [program] start a program'",
                "endif",
                "if {v:category == 'File'}",
                "out 'croak [file]. . . . . . . . .deletes the file'",
                "out 'hatch [file]. . . . . . . . .creates a file'",
                "out 'meta [file] . . . . . . . . .edits a file'",
                "out 'metaprop [file] [perm] [0/1] edits a file\'s properties'",
                "out 'spy [file]. . . . . . . . . .reads the file'",
                "endif",
                "if {v:category == 'Directory'}",
                "out 'spawn [directory] creates a directory'",
                "out 'hop [directory]. .moves to a directory'",
                "endif",
                "if {v:category == 'Other'}",
                "out 'changepalette [palette] changes the color palette'",
                "out 'clear. . . . . . . . . .clears the terminal output'",
                "out 'macro [macro]. . . . . .runs a macro'",
                "out 'ribbit [text]. . . . . .displays the text'",
                "out 'formattime [format]. . .changes the time format'",
                "out 'clearterminal' . . . . .clears the terminal output'",
                "endif",
                "endprog",
            ] },
            { name: "kaerugotchi", properties: {read: true, write: true, hidden: false}, data: [
                "str currentEmotion = 'default'",
                "str currentAction = 'play'",
                "",
                "int selectedPromptOption = 0",
                "",
                "str quitFailsafe = ''",
                "",
                "int coin = 30",
                "int energy = 60",
                "int hunger = 60",
                "int happiness = 20",
                "",
                "int decayTimer = 0",
                "",
                "str coinDisplay = ''",
                "str energyDisplay = ''",
                "str hungerDisplay = ''",
                "str happinessDisplay = ''",
                "",
                "int energyIterator = 0",
                "int hungerIterator = 0",
                "int happinessIterator = 0",
                "",
                "func body",
                "    out ' (----)'",
                "    out '(>____<)'",
                "    out ' ^^~~^^'",
                "endfunc",
                "",
                "func hungryBody",
                "    out ' (~~~~)'",
                "    out '(>____<)'",
                "    out ' ^^~~^^'",
                "endfunc",
                "",
                "func headDefault",
                "    out '  o..o'",
                "endfunc",
                "",
                "func headDrowsy",
                "    out '  =..='",
                "endfunc",
                "",
                "func headSleepy",
                "    out '  _.._ .zZ'",
                "endfunc",
                "",
                "func headHappy",
                "    out '  ^..^'",
                "endfunc",
                "",
                "func headConfused",
                "    out '  @..@'",
                "endfunc",
                "",
                "func headAngry",
                "    out '  >..<'",
                "endfunc",
                "",
                "func headSad",
                "    out '  q..q'",
                "endfunc",
                "",
                "func headUnamused",
                "    out '  -..-'",
                "endfunc",
                "",
                "",
                "loop { true }",
                "    clearterminal",
                "    set coinDisplay = '     coin:'",
                "    set energyDisplay = '   energy: '",
                "    set hungerDisplay = '   hunger: '",
                "    set happinessDisplay = 'happiness: '",
                "",
                "    set energyIterator = 0",
                "    set hungerIterator = 0",
                "    set happinessIterator = 0",
                "",
                "    loop { v:energyIterator < v:energy }",
                "        append energyDisplay '_'",
                "        set energyIterator = v:energyIterator + 1",
                "    endloop",
                "",
                "    loop {v:hungerIterator < v:hunger}",
                "        append hungerDisplay '_'",
                "        set hungerIterator = v:hungerIterator + 1",
                "    endloop",
                "",
                "    loop {v:happinessIterator < v:happiness}",
                "        append happinessDisplay '_'",
                "        set happinessIterator = v:happinessIterator + 1",
                "    endloop",
                "",
                "    outc {t=c06} 'v:coinDisplay v:coin'",
                "    outc {t=c09 | b=c09, br=11-71} 'v:energyDisplay'",
                "    outc {t=c12 | b=c12, br=11-71} 'v:hungerDisplay'",
                "    outc {t=c13 | b=c13, br=11-71} 'v:happinessDisplay'",
                "",
                "    out ''",
                "",
                "    if {v:currentEmotion == 'sleepy'}",
                "        f: headSleepy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'default'}",
                "        f: headDefault",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'happy'}",
                "        f: headHappy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'confused'}",
                "        f: headConfused",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'angry'}",
                "        f: headAngry",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'sad'}",
                "        f: headSad",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'unamused'}",
                "        f: headUnamused",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'drowsy'}",
                "        f: headDrowsy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'hungry'}",
                "        f: headDefault",
                "        f: hungryBody",
                "    endif",
                "",
                "    if {v:currentEmotion == 'very_hungry'}",
                "        f: headConfused",
                "        f: hungryBody",
                "    endif",
                "",
                "    out v:currentEmotion",
                "    prompt selectedPromptOption currentAction play sleep feed work poke [[QUIT]]",
                "",
                "",
                "    if {v:currentAction == 'play'}",
                "        set selectedPromptOption = 0",
                "        if {v:energy > 1 && v:happiness < 60 }",
                "            set happiness = v:happiness + 1",
                "            set energy = v:energy - 1",
                "        endif",
                "    endif",
                "",
                "    if {v:currentAction == 'sleep'}",
                "        set selectedPromptOption = 1",
                "        if {v:hunger > 1 && v:energy < 60 }",
                "            set energy = v:energy + 1",
                "            set hunger = v:hunger - 1",
                "        endif",
                "    endif",
                "",
                "    if {v:currentAction == 'feed'}",
                "        set selectedPromptOption = 2",
                "        if {v:coin > 1 && v:hunger < 60}",
                "            set hunger = v:hunger + 1",
                "            set coin = v:coin - 2",
                "        endif",
                "    endif",
                "",
                "    if {v:currentAction == 'work'}",
                "        set selectedPromptOption = 3",
                "        if {v:energy > 2 && v:hunger > 2 && v:happiness > 2}",
                "            set hunger = v:hunger - 2",
                "            set energy = v:energy - 2",
                "            set happiness = v:happiness - 2",
                "            set coin = v:coin + 10",
                "        endif",
                "    endif",
                "",
                "    if {v:currentAction == 'poke'}",
                "        set selectedPromptOption = 4",
                "        set currentEmotion = 'angry'",
                "    endif",
                "",
                "    if {v:hunger > 15}",
                "        set currentEmotion = 'default'",
                "    endif",
                "    if {v:happiness <= 10}",
                "        set currentEmotion = 'sad'",
                "    endif",
                "    if {v:happiness >= 50}",
                "        set currentEmotion = 'happy'",
                "    endif",
                "    if {v:energy <= 20}",
                "        set currentEmotion = 'drowsy'",
                "    endif",
                "    if {v:energy < 10}",
                "        set currentEmotion = 'sleepy'",
                "    endif",
                "    if {v:hunger <= 15}",
                "        set currentEmotion = 'hungry'",
                "    endif",
                "    if {v:hunger < 5}",
                "        set currentEmotion = 'very_hungry'",
                "    endif",
                "",
                "    if {v:currentAction == '[[QUIT]]'}",
                "        out 'Are you sure you want to quit?'",
                "        prompt 0 quitFailsafe no yes",
                "        if {v:quitFailsafe == 'yes'}",
                "            savedata coin",
                "            savedata energy",
                "            savedata hunger",
                "            savedata happiness",
                "            clearterminal",
                "            endprog",
                "        endif",
                "        set quitFailsafe = ''",
                "    endif",
                "",
                "   if {v:energy > 60}",
                "       set energy = 60",
                "   endif",
                "   if {v:energy < 0}",
                "       set energy = 0",
                "   endif",
                "   if {v:hunger > 60}",
                "       set hunger = 60",
                "   endif",
                "   if {v:hunger < 0}",
                "       set hunger = 0",
                "   endif",
                "   if {v:happiness > 60}",
                "       set happiness = 60",
                "   endif",
                "   if {v:happiness < 0}",
                "       set happiness = 0",
                "   endif",
                "   set decayTimer = v:decayTimer + 1",
                "endloop",
                "endprog"
            ] },
        ],
        "D:/Macros": [
            { name: "create-program", properties: {read: true, write: true, hidden: false}, data: [
                "!c",
                "h D:/Programs",
                "ch $1",
                "m $1"
            ] },
            { name: "edit-program", properties: {read: true, write: true, hidden: false}, data: [
                "!e",
                "h D:/Programs",
                "m $1"
            ] },
            { name: "reload", properties: {read: true, write: true, hidden: false}, data: [
                "!r",
                "[[BULLFROG]]urgentsavestate",
                "[[BULLFROG]]urgentloadstate",
                "[[BULLFROG]]urgentclearstate",
                "clear",
                "ribbit OS state reloaded"
            ] },
            { name: "edit-settings", properties: {read: true, write: true, hidden: false}, data: [
                "!es",
                "h Settings:",
                "m $1",
            ] },
            { name: "edit-palette", properties: {read: true, write: true, hidden: false}, data: [
                "!ep",
                "h D:/Palettes",
                "m $1",
            ] },
        ],
        "D:/Program-Data": [],
        "D:/Palettes": [
            // standard and revised palettes:  https://int10h.org/blog/2022/06/ibm-5153-color-true-cga-palette/
            { name: "standard", properties: {read: true, write: true, hidden: false}, data: [
                "000000", // 00 black
                "0000AA", // 01 blue
                "00AA00", // 02 green
                "00AAAA", // 03 cyan
                "AA0000", // 04 red
                "AA00AA", // 05 magenta
                "AA5500", // 06 brown
                "AAAAAA", // 07 light grey
                "555555", // 08 dark grey
                "5555FF", // 09 light blue
                "55FF55", // 10 light green
                "55FFFF", // 11 light cyan
                "FF5555", // 12 light red
                "FF55FF", // 13 light magenta
                "FFFF55", // 14 yellow
                "FFFFFF", // 15 white
            ] },
            { name: "revised", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "0000C4",
                "00C400",
                "00C4C4",
                "C40000",
                "C400C4",
                "C47E00",
                "C4C4C4",
                "4E4E4E",
                "4E4EDC",
                "4EDC4E",
                "4EF3F3",
                "DC4E4E",
                "F34EF3",
                "F3F34E",
                "FFFFFF",
            ] },
            { name: "standard-dark", properties: {read: true, write: true, hidden: false}, data: [
                "000000", // 00 black (unchanged)
                "000066", // 01 dark blue
                "006600", // 02 dark green
                "006666", // 03 dark cyan
                "660000", // 04 dark red
                "660066", // 05 dark magenta
                "664400", // 06 dark brown
                "666666", // 07 grey
                "222222", // 08 darker grey
                "222288", // 09 deep blue
                "228822", // 10 deep green
                "228888", // 11 deep cyan
                "882222", // 12 deep red
                "882288", // 13 deep magenta
                "888822", // 14 deep yellow
                "AAAAAA", // 15 light grey (less bright than white)
            ] },
            { name: "cherry", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "1C219F",
                "289E42",
                "17ABAE",
                "E48579",
                "980C6C",
                "BC3517",
                "C2C5C6",
                "464C50",
                "5790E4",
                "FF9F58",
                "68DCCD",
                "831326",
                "D97BC7",
                "B7EA8A",
                "FFFFFF",
            ] },
            { name: "swamp", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "4B71AF",
                "3F9A44",
                "3B9994",
                "DEA4A5",
                "9A3F95",
                "C27E4B",
                "B2B2B2",
                "6C6C6C",
                "96A2CF",
                "93C495",
                "AECFCD",
                "984547",
                "D7ABD4",
                "D6B87B",
                "FFFFFF",
            ] },
            { name: "swamp-revised", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "31618D",
                "298B27",
                "268B67",
                "D3977F",
                "773669",
                "BF833A",
                "97A791",
                "465C3F",
                "8DBDD5",
                "81CB7D",
                "91C9B9",
                "753B29",
                "CBA9DB",
                "D7D357",
                "FFFFFF",
            ] },
            { name: "neon", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "0000FF",
                "00FF00",
                "00FFFF",
                "FF0000",
                "FF00FF",
                "FFA500",
                "ABABAB",
                "757575",
                "5555FF",
                "55FF55",
                "55FFFF",
                "FF5555",
                "FF55FF",
                "FFFF55",
                "FFFFFF",
            ] },
        ],
        "D:/Spinners": [
            { name: "default", properties: {read: true, write: true, hidden: false}, data: [
                '-', '\\', '|', '/'
            ] },
            { name: "dots", properties: {read: true, write: true, hidden: false}, data: [
                ".", ":", "¨", ":"
            ] },
            { name: "circles", properties: {read: true, write: true, hidden: false}, data: [
                ".", "o", "O", "°", "O", "o"
            ] },
            { name: "cross", properties: {read: true, write: true, hidden: false}, data: [
                "×", "+"
            ] },
            { name: "wave", properties: {read: true, write: true, hidden: false}, data: [
                "~", "–"
            ] },
            { name: "arrows", properties: {read: true, write: true, hidden: false}, data: [
                "<", "^", ">", "v"
            ] },
            { name: "shade", properties: {read: true, write: true, hidden: false}, data: [
                "·", ":", "!", "+", "x", "%", "#", "%", "x", "+", "!", ":"
            ] }
        ],
    }
}
