const config = {
    debugMode: false,
    version: "1.5",
    colorPalette: "standard",
    currentPath: 'C:/Home',
    commandHistory: [],
    commandHistoryIndex: -1,
    showLoadingSpinner: false,
    timeFormat: 'w. y/M/d h:m:s',
    updateStatBar: true,
    currentProgram: "cli",
    programList: ["cli", "lilypad"],
    allowedProgramDirectories: ["D:/Programs"],
    dissallowSubdirectoriesIn: ["D:/Programs", "D:/Macros", "D:/Program-Data", "D:/Palettes"],
    programSession: 0,
    errorText: "<span class='error'><span class='error-text'>!!ERROR!!</span> -</span>",
    fileSystem: {
        "C:": [], 
        "C:/Home": [
            { name: "welcome!", properties: {read: true, write: true, hidden: false}, data: ['Hello!', "Welcome to FroggyOS.", "Type 'help' for a list of commands.", "Have fun! ^v^"] },
        ],
        "C:/Docs": [],
        "D:": [], 
        "D:/Programs": [
            { name: "cli", properties: {read: false, write: false, hidden: true}, data: ["str cli = 'this program is hardcoded into froggyOS'", "endprog"] },
            { name: "lilypad", properties: {read: false, write: false, hidden: true}, data: ["str lilypad = 'this program is hardcoded into froggyOS'", "endprog"] },
            { name: "help", properties: {read: true, write: false, hidden: false}, data: [
                "str category = ''",
                "out 'Choose a category: '",
                "prompt 0 category OS File Directory Other",
                "if {v:category == 'OS'}",
                "out 'clearstate. . . .clears froggyOS state'",
                "out 'loadstate . . . .loads froggyOS state'",
                "out 'savestate . . . .saves froggyOS state'",
                "out 'swimto [program] start a program'",
                "endif",
                "if {v:category == 'File'}",
                "out 'croak [file]. . . . . . . . .deletes the file'",
                "out 'hatch [file]. . . . . . . . .creates a file'",
                "out 'meta [file] . . . . . . . . .edits a file'",
                "out 'metaprop [file] [perm] [0/1] edits a file\'s properties'",
                "out 'spy [file]. . . . . . . . . .reads the file'",
                "endif",
                "if {v:category == 'Directory'}",
                "out 'spawn [directory] creates a directory'",
                "out 'hop [directory]. .moves to a directory'",
                "endif",
                "if {v:category == 'Other'}",
                "out 'changepalette [palette] changes the color palette'",
                "out 'clear. . . . . . . . . .clears the terminal output'",
                "out 'macro [macro]. . . . . .runs a macro'",
                "out 'ribbit [text]. . . . . .displays the text'",
                "out 'formattime [format]. . .changes the time format'",
                "out 'clearterminal' . . . . .clears the terminal output'",
                "endif",
                "endprog",
            ] },
            { name: "test", properties: {read: true, write: true, hidden: false}, data: [
                "func meow",
                "    out 'meow meow!'",
                "    out 'purrrrr'",
                "endfunc",
                "func bark",
                "    out 'bark bark!'",
                "    out 'grrrrr'",
                "endfunc",
                "f: meow",
                "f: bark",
                "endprog",

            ] },
            { name: "demo", properties: {read: true, write: true, hidden: true}, data: [
                "str field = ''",

                "int field_x = 0",
                "int player_x = 0",

                "str playerAction = 'right'",
                "int selectedOption = 0",

                "str fieldBackground = '.'",
                "str playerChar = '^-^'",

                "str quitConfirm = ''",


                "loop { true }",
                "    -- field generation",
                "    loop {v:field_x < 75}",
                "        if {v:field_x == v:player_x}",
                "            append field v:playerChar",
                "        else",
                "            append field v:fieldBackground",
                "        endif",
                "        set field_x = v:field_x + 1",
                "    endloop",

                "    clearterminal",

                "    out v:field",
                "    out ''",

                "    set field_x = 0",

                "    prompt selectedOption playerAction left right [[QUIT]]",
                "    if {v:playerAction == 'left' && v:player_x > 0}",
                "        set playerAction = 'left'",
                "        set player_x = v:player_x - 1",
                "        set selectedOption = 0",
                "    endif",

                "    if {v:playerAction == 'right' && v:player_x < 74}",
                "        set playerAction = 'right'",
                "        set player_x = v:player_x + 1",
                "        set selectedOption = 1",
                "    endif",

                "    if {v:playerAction == '[[QUIT]]'}",
                "        out 'Are you sure you want to quit?'",
                "        prompt 0 quitConfirm no yes",
                "        if {v:quitConfirm == 'yes'}",
                "            clearterminal",
                "            endprog",
                "        endif",
                "        set quitConfirm = ''",
                "    endif",

                "    set field = ''",
                "endloop",
            ] },
            { name: "kaerugotchi", properties: {read: true, write: true, hidden: false}, data: [
                "str currentEmotion = 'default'",
                "str currentAction = 'play'",
                "",
                "int selectedPromptOption = 0",
                "",
                "str quitFailsafe = ''",
                "",
                "int energy = 60",
                "int hunger = 60",
                "int happiness = 60",
                "",
                "str energyDisplay = '   energy: '",
                "str hungerDisplay = '   hunger: '",
                "str happinessDisplay = 'happiness: '",
                "",
                "int energyIterator = 0",
                "int hungerIterator = 0",
                "int happinessIterator = 0",
                "",
                "func body",
                "out ' (----)'",
                "out '(>____<)'",
                "out ' ^^~~^^'",
                "endfunc",
                "",
                "func hungryBody",
                "out ' (~~~~)'",
                "out '(>____<)'",
                "out ' ^^~~^^'",
                "endfunc",
                "",
                "func headDefault",
                "out '  o..o'",
                "endfunc",
                "",
                "func headDrowsy",
                "out '  =..='",
                "endfunc",
                "",
                "func headSleepy",
                "out '  _.._ .zZ'",
                "endfunc",
                "",
                "func headHappy",
                "out '  ^..^'",
                "endfunc",
                "",
                "func headConfused",
                "out '  @..@'",
                "endfunc",
                "",
                "func headAngry",
                "out '  >..<'",
                "endfunc",
                "",
                "func headSad",
                "out '  q..q'",
                "endfunc",
                "",
                "func headUnamused",
                "out '  -..-'",
                "endfunc",
                "",
                "",
                "loop { true }",
                "    clearterminal",
                "    set energyDisplay = '   energy: '",
                "    set hungerDisplay = '   hunger: '",
                "    set happinessDisplay = 'happiness: '",
                "",
                "    set energyIterator = 0",
                "    set hungerIterator = 0",
                "    set happinessIterator = 0",
                "",
                "    loop {v:energyIterator < v:energy}",
                "        append energyDisplay '#'",
                "        set energyIterator = v:energyIterator + 1",
                "    endloop",
                "",
                "    loop {v:hungerIterator < v:hunger}",
                "        append hungerDisplay '#'",
                "        set hungerIterator = v:hungerIterator + 1",
                "    endloop",
                "",
                "    loop {v:happinessIterator < v:happiness}",
                "        append happinessDisplay '#'",
                "        set happinessIterator = v:happinessIterator + 1",
                "    endloop",
                "",
                "",
                "    outc c09 v:energyDisplay",
                "    outc c12 v:hungerDisplay",
                "    outc c13 v:happinessDisplay",
                "",
                "    out ''",
                "    if {v:currentEmotion == 'default'}",
                "        f: headDefault",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'sleepy'}",
                "        f: headSleepy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'happy'}",
                "        f: headHappy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'confused'}",
                "        f: headConfused",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'angry'}",
                "        f: headAngry",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'sad'}",
                "        f: headSad",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'unamused'}",
                "        f: headUnamused",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'drowsy'}",
                "        f: headDrowsy",
                "        f: body",
                "    endif",
                "",
                "    if {v:currentEmotion == 'hungry'}",
                "        f: headDefault",
                "        f: hungryBody",
                "    endif",
                "",
                "    if {v:currentEmotion == 'very_hungry'}",
                "        f: headConfused",
                "        f: hungryBody",
                "    endif",
                "",
                "    prompt selectedPromptOption currentAction play sleep feed work poke [[QUIT]]",
                "",
                "    if {v:happiness > 50}",
                "        set currentEmotion = 'happy'",
                "    endif",
                "    if {v:happiness > 20 && v:happiness < 50}",
                "        set currentEmotion = 'default'",
                "    endif",
                "    if {v:happiness > 5 && v:happiness < 20}",
                "        set currentEmotion = 'unamused'",
                "    endif",
                "    if {v:happiness <= 5}",
                "        set currentEmotion = 'sad'",
                "    endif",
                "    if {v:energy < 20}",
                "        set currentEmotion = 'drowsy'",
                "    endif",
                "    if {v:energy <= 5}",
                "        set currentEmotion = 'sleepy'",
                "    endif",
                "    if {v:hunger < 15 && v:hunger > 5}",
                "        set currentEmotion = 'hungry'",
                "    endif",
                "    if {v:hunger <= 5}",
                "        set currentEmotion = 'very_hungry'",
                "    endif",
                "",
                "    if {v:currentAction == 'play' && v:energy > 1}",
                "        set selectedPromptOption = 0",
                "        set happiness = v:happiness + 1",
                "        set energy = v:energy - 1",
                "    endif",
                "",
                "    if {v:currentAction == 'sleep'}",
                "        set selectedPromptOption = 1",
                "        set energy = v:energy + 1",
                "        set hunger = v:hunger - 1",
                "        set currentEmotion = 'sleepy'",
                "    endif",
                "",
                "    if {v:currentAction == 'feed'}",
                "        set selectedPromptOption = 2",
                "        set hunger = v:hunger + 1",
                "    endif",
                "",
                "    if {v:currentAction == 'work'}",
                "        set selectedPromptOption = 3",
                "        set hunger = v:hunger - 2",
                "        set energy = v:energy - 2",
                "        set happiness = v:happiness - 2",
                "    endif",
                "",
                "    if {v:currentAction == 'poke'}",
                "        set selectedPromptOption = 4",
                "        set currentEmotion = 'angry'",
                "    endif",
                "",
                "    if {v:currentAction == '[[QUIT]]'}",
                "        out 'Are you sure you want to quit?'",
                "        prompt 0 quitFailsafe no yes",
                "        if {v:quitFailsafe == 'yes'}",
                "            clearterminal",
                "            endprog",
                "        endif",
                "        set quitFailsafe = ''",
                "    endif",
                "",
                "   if {v:energy > 60}",
                "       set energy = 60",
                "   endif",
                "   if {v:energy < 0}",
                "       set energy = 0",
                "   endif",
                "   if {v:hunger > 60}",
                "       set hunger = 60",
                "   endif",
                "   if {v:hunger < 0}",
                "       set hunger = 0",
                "   endif",
                "   if {v:happiness > 60}",
                "       set happiness = 60",
                "   endif",
                "   if {v:happiness < 0}",
                "       set happiness = 0",
                "   endif",
                "endloop",
                "endprog"
            ] }, // FIIIIIX!!!!!!!!!!!!!!!! SOMETHING DEFINITELY WRONG HERE
        ],
        "D:/Macros": [
            { name: "create-program", properties: {read: true, write: true, hidden: false}, data: [
                "!c",
                "h D:/Programs",
                "ch $1",
                "m $1"
            ] },
            { name: "edit-program", properties: {read: true, write: true, hidden: false}, data: [
                "!e",
                "h D:/Programs",
                "m $1"
            ] },
        ],
        "D:/Program-Data": [],
        "D:/Palettes": [
            // standard and revised palettes:  https://int10h.org/blog/2022/06/ibm-5153-color-true-cga-palette/
            { name: "standard", properties: {read: true, write: true, hidden: false}, data: [
                "000000", // 00 black
                "0000AA", // 01 blue
                "00AA00", // 02 green
                "00AAAA", // 03 cyan
                "AA0000", // 04 red
                "AA00AA", // 05 magenta
                "AA5500", // 06 brown
                "AAAAAA", // 07 light grey
                "555555", // 08 dark grey
                "5555FF", // 09 light blue
                "55FF55", // 10 light green
                "55FFFF", // 11 light cyan
                "FF5555", // 12 light red
                "FF55FF", // 13 light magenta
                "FFFF55", // 14 yellow
                "FFFFFF", // 15 white
            ] },
            { name: "revised", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "0000C4",
                "00C400",
                "00C4C4",
                "C40000",
                "C400C4",
                "C47E00",
                "C4C4C4",
                "4E4E4E",
                "4E4EDC",
                "4EDC4E",
                "4EF3F3",
                "DC4E4E",
                "F34EF3",
                "F3F34E",
                "FFFFFF",
            ] },
            { name: "cherry", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "1C219F",
                "289E42",
                "17ABAE",
                "E48579",
                "980C6C",
                "BC3517",
                "C2C5C6",
                "464C50",
                "5790E4",
                "FF9F58",
                "68DCCD",
                "831326",
                "D97BC7",
                "B7EA8A",
                "FFFFFF",
            ] },
            { name: "swamp", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "4B71AF",
                "3F9A44",
                "3B9994",
                "DEA4A5",
                "9A3F95",
                "C27E4B",
                "B2B2B2",
                "6C6C6C",
                "96A2CF",
                "93C495",
                "AECFCD",
                "984547",
                "D7ABD4",
                "D6B87B",
                "FFFFFF",
            ] },
            { name: "swamp-revised", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "31618D",
                "298B27",
                "268B67",
                "D3977F",
                "773669",
                "BF833A",
                "97A791",
                "465C3F",
                "8DBDD5",
                "81CB7D",
                "91C9B9",
                "753B29",
                "CBA9DB",
                "D7D357",
                "FFFFFF",
            ] },
            { name: "neon", properties: {read: true, write: true, hidden: false}, data: [
                "000000",
                "0000FF",
                "00FF00",
                "00FFFF",
                "FF0000",
                "FF00FF",
                "FFA500",
                "ABABAB",
                "757575",
                "5555FF",
                "55FF55",
                "55FFFF",
                "FF5555",
                "FF55FF",
                "FFFF55",
                "FFFFFF",
            ] },
        ]
    }
};